// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5W11tA81NOmNL7WINYRtdp_1mh0JGCtw',
    appId: '1:509024607125:web:654fb64591529d1269749c',
    messagingSenderId: '509024607125',
    projectId: 'basic-calculator-faf04',
    authDomain: 'basic-calculator-faf04.firebaseapp.com',
    storageBucket: 'basic-calculator-faf04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuUrWQHd2VTskrEDO3eSPhHQ6UmA1oX0',
    appId: '1:509024607125:android:19e4627273ec556e69749c',
    messagingSenderId: '509024607125',
    projectId: 'basic-calculator-faf04',
    storageBucket: 'basic-calculator-faf04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHJyclxkFlK6mwSKM5uhUyytiDHlf3VDY',
    appId: '1:509024607125:ios:0f327afe95b5afc769749c',
    messagingSenderId: '509024607125',
    projectId: 'basic-calculator-faf04',
    storageBucket: 'basic-calculator-faf04.firebasestorage.app',
    iosBundleId: 'com.anuragborker.basicCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHJyclxkFlK6mwSKM5uhUyytiDHlf3VDY',
    appId: '1:509024607125:ios:eb61a64ce500215869749c',
    messagingSenderId: '509024607125',
    projectId: 'basic-calculator-faf04',
    storageBucket: 'basic-calculator-faf04.firebasestorage.app',
    iosBundleId: 'com.example.basicCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5W11tA81NOmNL7WINYRtdp_1mh0JGCtw',
    appId: '1:509024607125:web:992614ea986c271e69749c',
    messagingSenderId: '509024607125',
    projectId: 'basic-calculator-faf04',
    authDomain: 'basic-calculator-faf04.firebaseapp.com',
    storageBucket: 'basic-calculator-faf04.firebasestorage.app',
  );
}
